# Site settings
title: Alex Coady
email: alex@coady.me
description: > # this means to ignore newlines until "baseurl:"
  Alex Coady is a web developer based in London, UK.
copyright: "&copy; Alex Coady 2015"
baseurl: "" # the subpath of your site, e.g. /blog/
imagesrc: "/images/"
url: "http://coady.me" # the base hostname & protocol for your site
twitter_username: coadycodes
github_username: alexcoady
stackoverflow_username: alex
codepen_username: alexcoady
stackoverflow_url: http://stackoverflow.com/users/687581/alex
permalink: pretty

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      imagesrc: "/images/"
      intro: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      excerpt_separator: <!--more-->
      imagesrc: "/images/posts/"
      intro: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
