# Site settings
title: Alex Coady
email: alex@coady.me
description: > # this means to ignore newlines until "baseurl:"
  Alex Coady is a web developer based in London, UK.
baseurl: "" # the subpath of your site, e.g. /blog/
imagesrc: /images/ # the subpath of your site, e.g. /blog/
url: "http://coady.me" # the base hostname & protocol for your site
twitter_username: coadycodes
github_username:  alexcoady

# Build settings
markdown: kramdown
